### ISSUE TITLE
install linter

### ISSUE THREAD

**Issue by haithhawk** [FACN3/al-shams#55]
linter isn't installed in your project 
here is how you install it : https://github.com/foundersandcoders/master-reference/blob/master/coursebook/week-5/linter.md

**Comment by Amirk390** [comment]
Thanks, its an important point
Luckily, we already did it before we started coding :smile: 

https://github.com/FACN3/al-shams/blob/master/package.json#L21

```
  "homepage": "https://github.com/FACN3/al-shams#readme",
  "devDependencies": {
    "eslint": "^4.12.0",
    "nodemon": "^1.12.1",
    "nyc": "^11.3.0",
    "shot": "^3.4.0",
    "tap-spec": "^4.1.1",
    "tape": "^4.8.0"
```
